version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '10:00'
    open-pull-requests-limit: 10
    groups:
      dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      nx:
        patterns:
          - "nx"
          - "@nx/*"
        update-types:
          - "major"
      storybook:
        patterns:
          - "@storybook/*"
        update-types:
          - "major"
      versioning:
        patterns:
          - "@commitlint/*"
          - "@jscutlery/semver"
          - "conventional-changelog-*"
        update-types:
          - "major"
      jest:
        patterns:
          - "jest"
          - "*jest*"
        update-types:
          - "major"
