version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gh-actions:
        update-types:
          - "minor"
          - "patch"
          - "major"
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '10:00'
    open-pull-requests-limit: 10
    groups:
      mui:
        patterns:
          - "@mui/*"
        exclude-patterns:
          - "@mui/x-*"
      nx:
        patterns:
          - "nx"
          - "@nx/*"
      storybook:
        patterns:
          - "@storybook/*"
          - "*storybook*"
      versioning:
        patterns:
          - "@commitlint/*"
          - "@jscutlery/semver"
          - "conventional-changelog-*"
      jest:
        patterns:
          - "jest"
          - "*jest*"
      dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
