nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.3.1.cjs

npmPublishRegistry: 'https://registry.npmjs.org/'

npmRegistryServer: 'https://registry.npmjs.org/'

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - musl
    - glibc
  os:
    - current
    - linux
    - darwin
    - win32
